[biophysical_constants]
transcription_saturation_constant=0.36                  # units: µM
characteristic_transcript_length=1000                   # units: nt 
mRNA_half_life_in_min = "need_to_fill_me_in"            # units: hr
RNAPII_concentration="need_to_fill_me_in"               # units: µM
transcription_elongation_rate="need_to_fill_me_in"      # units: nt/s
